#ifndef COSTANTI_H_
#define COSTANTI_H_

#define DIMENSIONE_MASSIMA_PERCORSO 90
#define DIMENSIONE_MINIMA_PERCORSO 50
#define NUMERO_MASSIMO_GIOCATORI 4
#define NUMERO_MINIMO_GIOCATORI 2
#define FACCIA_MINIMA_DADO 1
#define FACCIA_MASSIMA_DADO 6
#define NUMERO_DADI 2
#define DISTANZA_OCHE 9
#define NUMERO_CASELLE_SPECIALI 7
#define PRIMO_DADO 1
#define NUMERO_MASSIMO_CARATTERI_SIMBOLO 5
#define ALTEZZA_DISEGNO_CASELLA 3
#define LARGHEZZA_DISEGNO_CASELLA 5
#define SPAZIO_DISPONIBILE_CASELLA 4
#define LARGHEZZA_TABELLONE 15
#define ALTEZZA_TABELLONE 6
#define PRIMO_LANCIO_3_6 38
#define PRIMO_LANCIO_4_5 76
#define DADO_MINORE_PRIMO_LANCIO 3
#define DADO_MAGGIORE_PRIMO_LANCIO 6
#define TURNI_ATTESA_LOCANDA 3
#define CASELLA_ARRIVO_LABIRINTO 33
#define CASELLA_ARRIVO_SCHELETRO 1
#define DADO_MINORE_USCITA_PRIGIONE 5
#define DADO_MAGGIORE_USCITA_PRIGIONE 7
#define DIMENSIONE_MINIMA_NOME_PARTITA 3
#define DIMENSIONE_MASSIMA_NOME_PARTITA 12
#define DIMENSIONE_MINIMA_NOME_GIOCATORE 3
#define DIMENSIONE_MASSIMA_NOME_GIOCATORE 18
#define DIMENSIONE_MASSIMA_NOME_CASELLA 9
#define NUMERO_MASSIMO_PARTITE 5
#define NUMERO_MASSIMO_CLASSIFICATI 10
#define MOLTIPLICATORE 1664525
#define INCREMENTO 1013904223
#define DIVISORE 4294367296
#define BASE 10



#define NUMERO_MASSIMO_CARATTERI_PERCORSO 256
#define CARATTERE_SPAZIO " "
#define NUMERO_MASSIMO_OPZIONI_PRINCIPALE  5
#define NUMERO_MASSIMO_OPZIONI_AIUTO  2
#define POSIZIONE_GIOCATORE_1 1
#define POSIZIONE_GIOCATORE_2 2
#define POSIZIONE_GIOCATORE_3 3
#define POSIZIONE_GIOCATORE_4 4
#define NUMERO_GIOCATORI_STRATO_CASELLA 2
#define LUNGHEZZA_SCHERMATA 80
#define ALTEZZA_SCHERMATA 25
#define RISPOSTA_AFFERMATIVA_MAIUSCOLO 'S'
#define RISPOSTA_AFFERMATIVA_MINUSCOLO 's'
#define RISPOSTA_NEGATIVA_MAIUSCOLO 'N'
#define RISPOSTA_NEGATIVA_MINUSCOLO 'n'
#define FALSE 0
#define TRUE 1
#define FINE_FILE EOF

const char FINE_STRINGA = '\0';
const char CARATTERE_A_CAPO = '\n';
const char NOME_OCA[DIMENSIONE_MASSIMA_NOME_CASELLA] = "OCA\0";
const char NOME_PRIGIONE[DIMENSIONE_MASSIMA_NOME_CASELLA] = "PRIGIONE\0";
const char NOME_PONTE[DIMENSIONE_MASSIMA_NOME_CASELLA] = "PONTE\0";
const char NOME_LABIRINTO[DIMENSIONE_MASSIMA_NOME_CASELLA] = "LABIRINTO\0";
const char NOME_LOCANDA[DIMENSIONE_MASSIMA_NOME_CASELLA] = "LOCANDA\0";
const char NOME_POZZO[DIMENSIONE_MASSIMA_NOME_CASELLA] = "POZZO\0";
const char NOME_SCHELETRO[DIMENSIONE_MASSIMA_NOME_CASELLA] = "SCHELETRO\0";
const char NOME_VITTORIA[DIMENSIONE_MASSIMA_NOME_CASELLA] = "VITTORIA\0";
const char PEDINE_DISPONIBILI[NUMERO_MASSIMO_GIOCATORI] = "#$%&";
const char CONTORNO_LATERALE_CASELLA = ''|';
const char CONTORNO_SUPERIORE_CASELLA = '_';
const char CONTORNO_INFERIORE_CASELLA = '_';
