/*
 * costanti.h
 *
 */

#ifndef COSTANTI_H_
#define COSTANTI_H_

#define DIMENSIONE_MASSIMA_PERCORSO 90
#define DIMENSIONE_MINIMA_PERCORSO 50
#define NUMERO_MASSIMO_GIOCATORI 4
#define NUMERO_MINIMO_GIOCATORI 2
#define FACCIA_MINIMA_DADO 1
#define FACCIA_MASSIMA_DADO 6
#define NUMERO_DADI 2
#define DISTANZA_OCHE 9
#define NUMERO_CASELLE_SPECIALI 7
#define PRIMO_DADO 1
#define NUMERO_MASSIMO_CARATTERI_SIMBOLO 5
#define ALTEZZA_DISEGNO_CASELLA 3
#define LARGHEZZA_DISEGNO_CASELLA 5
#define SPAZIO_DISPONIBILE_CASELLA 4
#define LARGHEZZA_TABELLONE 15
#define ALTEZZA_TABELLONE 6
#define PRIMO_LANCIO_3_6 38
#define PRIMO_LANCIO_4_5 76
#define DADO_MINORE_PRIMO_LANCIO 3
#define DADO_MAGGIORE_PRIMO_LANCIO 6
#define TURNI_ATTESA_LOCANDA 3
#define CASELLA_ARRIVO_LABIRINTO 33
#define CASELLA_ARRIVO_SCHELETRO 1
#define DADO_MINORE_USCITA_PRIGIONE 5
#define DADO_MAGGIORE_USCITA_PRIGIONE 7
#define DIMENSIONE_MINIMA_NOME_PARTITA 3
#define DIMENSIONE_MASSIMA_NOME_PARTITA 12
#define DIMENSIONE_MINIMA_NOME_GIOCATORE 3
#define DIMENSIONE_MASSIMA_NOME_GIOCATORE 18
#define DIMENSIONE_MASSIMA_NOME_CASELLA 10
#define NUMERO_MASSIMO_PARTITE 5
#define NUMERO_MASSIMO_CLASSIFICATI 10
#define MOLTIPLICATORE 1664525
#define INCREMENTO 1013904223
#define DIVISORE 4294367296
#define BASE 10
#define UNITA 1


#define NUMERO_MASSIMO_CARATTERI_PERCORSO 256
#define CARATTERE_SPAZIO " "
#define NUMERO_MASSIMO_OPZIONI_PRINCIPALE  5
#define NUMERO_MASSIMO_OPZIONI_AIUTO  2
#define POSIZIONE_GIOCATORE_1 1
#define POSIZIONE_GIOCATORE_2 2
#define POSIZIONE_GIOCATORE_3 3
#define POSIZIONE_GIOCATORE_4 4
#define NUMERO_GIOCATORI_STRATO_CASELLA 2
#define LUNGHEZZA_SCHERMATA 80
#define ALTEZZA_SCHERMATA 25
#define RISPOSTA_AFFERMATIVA_MAIUSCOLO 'S'
#define RISPOSTA_AFFERMATIVA_MINUSCOLO 's'
#define RISPOSTA_NEGATIVA_MAIUSCOLO 'N'
#define RISPOSTA_NEGATIVA_MINUSCOLO 'n'
#define FALSE 0
#define TRUE 1
#define FINE_FILE EOF
#define DIMENSIONE_MASSIMA_SIMBOLO_CASELLA 5

const char FINE_STRINGA = '\0';
const char CARATTERE_A_CAPO = '\n';
const char NOME_OCA[DIMENSIONE_MASSIMA_NOME_CASELLA] = "OCA\0";
const char NOME_PRIGIONE[DIMENSIONE_MASSIMA_NOME_CASELLA] = "PRIGIONE\0";
const char NOME_PONTE[DIMENSIONE_MASSIMA_NOME_CASELLA] = "PONTE\0";
const char NOME_LABIRINTO[DIMENSIONE_MASSIMA_NOME_CASELLA] = "LABIRINTO\0";
const char NOME_LOCANDA[DIMENSIONE_MASSIMA_NOME_CASELLA] = "LOCANDA\0";
const char NOME_POZZO[DIMENSIONE_MASSIMA_NOME_CASELLA] = "POZZO\0";
const char NOME_SCHELETRO[DIMENSIONE_MASSIMA_NOME_CASELLA] = "SCHELETRO\0";
const char NOME_VITTORIA[DIMENSIONE_MASSIMA_NOME_CASELLA] = "VITTORIA\0";
const char PEDINE_DISPONIBILI[NUMERO_MASSIMO_GIOCATORI] = "#$%&";
const char SIMBOLO_PONTE[DIMENSIONE_MASSIMA_SIMBOLO_CASELLA] = "==\0";
const char SIMBOLO_PRIGIONE[DIMENSIONE_MASSIMA_SIMBOLO_CASELLA] = "[#]\0";
const char SIMBOLO_LABIRINTO[DIMENSIONE_MASSIMA_SIMBOLO_CASELLA] = "@\0";
const char SIMBOLO_VITTORIA[DIMENSIONE_MASSIMA_SIMBOLO_CASELLA] = "W\0";
const char SIMBOLO_POZZO[DIMENSIONE_MASSIMA_SIMBOLO_CASELLA] = "(O)\0";
const char SIMBOLO_SCHELETRO[DIMENSIONE_MASSIMA_SIMBOLO_CASELLA] = "xx\0";
const char SIMBOLO_OCA[DIMENSIONE_MASSIMA_SIMBOLO_CASELLA] = "O\0";
const char SIMBOLO_LOCANDA[DIMENSIONE_MASSIMA_SIMBOLO_CASELLA] = "^^\0";
const char CONTORNO_LATERALE_CASELLA = '|';
const char CONTORNO_SUPERIORE_CASELLA = '_';
const char CONTORNO_INFERIORE_CASELLA = '_';
const char FILE_CLASSIFICA[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_classifica.txt";
const char FILE_CREDITI_6[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "crediti.txt";
const char FILE_MENU_AIUTO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_menu_aiuto.txt";
const char FINE_MANUALE[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_manuale.txt";
const char FILE_MENU_REGOLAMENTO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_menu_regolamento.txt";
const char FILE_PERCORSO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_percorso.txt";
const char FILE_REGOLE[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_regole.txt";
const char FINE_MENU_CARICA_PARTITA[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_menu_carica_partita.txt";
const char FILE_SCELTA_G_INIZIALE[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_scelta_g_iniziale.txt";
const char FILE_SCELTA_LUNG_PERCO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_scelta_lung_perco.txt";
const char FILE_SCELTA_N_GIOCATORI[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_scelta_n_giocatori.txt";
const char FILE_SCELTA_NOMI_GIOCATORI[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_scelta_nomi_giocatori.txt";
const char FILE_MENU_PRINCIPALE[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_menu_principale.txt";
const char FILE_SCELTA_NOME_PARTITA[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_scelta_nome_partita.txt";
const char FILE_SCELTA_SLOT_SALVARE_PARTITA[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_scelta_slot_salvare_partita.txt";
const char FILE_DETTAGLI_PARTITA[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_dettagli_partita.txt";
const char FILE_VITTORIA_NOMI[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_vittoria_nomi.txt";
const char FILE_INTRO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_intro.txt";
const char FILE_EASTEREGG1[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_easteregg1.txt";
const char FILE_EASTEREGG2[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_easteregg2.txt";
const char FILE_SCHERMATA_LABIRINTO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_labirinto.txt";
const char FILE_SCHERMATA_LANCIO_DADI_PRIGIONE[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_lancio_dadi_prigione.txt";
const char FILE_SCHERMATA_LIBERATO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_liberato.txt";
const char FILE_SCHERMATA_LOCANDA_TURNO_PASSATO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_locanda_turno_passato.txt";
const char FILE_SCHERMATA_LONCANDA[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_locanda.txt";
const char FILE_SCHERMATA_OCA[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_oca.txt";
const char FILE_SCHERMATA_PERM_POZZO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_perm_pozzo.txt";
const char FILE_SCHERMATA_PONTE[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_ponte.txt";
const char FILE_SCHERMATA_POZZO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_pozzo.txt";
const char FILE_SCHERMATA_PRIGIONE[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_prigione.txt";
const char FILE_SCHERMATA_SCHELETRO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_schermata_scheletro.txt";
const char FILE_CONFERMA_INSERIMENTO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_conferma_inserimento.txt";
const char FILE_CONFERMA_SALVATAGGIO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_conferma_salvataggio.txt";
const char FILE_RICHIESTA_C_INSERIMENTO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_richiesta_c_inserimento.txt";
const char FILE_RICHIESTA_C_SALVATAGGIO[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "file_richiesta_c_salvataggio.txt";
const char FILE_STAMPE[NUMERO_MASSIMO_CARATTERI_PERCORSO] = "stampe.txt";

#endif /* COSTANTI_H_ */
